# Generated by Django 5.0.7 on 2024-08-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_alter_profile_currentweb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webapp',
            name='pages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
