# Generated by Django 5.0.7 on 2024-08-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0003_alter_webapp_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentpage', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='webapp',
            name='pages',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
